# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XEngine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XEngine
pod "dsBridge"
 pod "LSRNetwork"
 pod "LSRFramework"
 pod 'SSZipArchive'
 pod 'XEngineAlertModuleTest'
end
