# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XEngine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XEngine
 	pod 'LSRFramework'
	pod 'JSONModel'
 	pod 'SSZipArchive'
	pod 'AFNetworking'
  target 'XEngineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XEngineUITests' do
    # Pods for testing
  end

end
